python -m netquery.dbgeo.train \
  --data_dir ./dbgeo/ \
  --model_dir ./model_dir/dbgeo_test/ \
  --log_dir ./model_dir/dbgeo_test/ \
  --embed_dim 0 \
  --depth 0 \
  --geo_info projbbox \
  --spa_enc_type theory \
  --enc_agg_type concat \
  --spa_embed_dim 64 \
  --freq 16 \
  --max_radius 5400000 \
  --min_radius 50 \
  --spa_f_act leakyrelu \
  --freq_init geometric \
  --spa_enc_use_postmat T \
  --spa_enc_embed_norm T \
  --anchor_sample_method fromid2geo \
  --num_rbf_anchor_pts 0 \
  --rbf_kernal_size 0 \
  --num_hidden_layer 1 \
  --hidden_dim 512 \
  --use_layn T \
  --skip_connection T \
  --dropout 0.5 \
  --decoder bilinear \
  --inter_decoder min_simple \
  --inter_decoder_atten_type concat_norm_postm \
  --inter_decoder_atten_act leakyrelu \
  --inter_decoder_atten_f_act sigmoid \
  --inter_decoder_atten_num 1 \
  --device cpu \
  --opt adam \
  --lr 0.001 \
  --batch_size 4096 \
  --val_every 1000 \
  --max_burn_in 20000 \
  --tol 1e-6 \
  --kg_train \
  --max_arity 7 \
  --geo_train \
  --edge_conv 
  # \
  # --load_model \
  # --eval_geo_log
